### PR TITLE
feat: package version management with Changeset

### LINKED ISSUE #225: chore: automate version management and package release
Explore semantic release bot for automated versioning and release

https://github.com/semantic-release/semantic-release

### PR DESCRIPTION
**Pull request by fazzaamiarso**
feat: package version management with Changeset

fix #225 

Description of changes: 
- install changeset cli
- add changeset github action

Tag a reviewer: @ayoayco 

Tasks:
- [ ] I have ran the build command to make sure apps are working: `npm run build`
- [ ] I have ran the tests to make sure nothing is broken: `npm run test`
- [ ] I have ran the linter to make sure code is clean: `npm run lint`
- [ ] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by fazzaamiarso** [comment]
@ayoayco I think changeset is great for version management in monorepo. Although, we must read the [docs](https://github.com/changesets/changesets/tree/main/docs) quite a bit to understand. But, it definitely improve the workflow.

I will start to add changeset bot and github action to automate. It will look something like [this PR](https://github.com/remix-run/remix/pull/4801) once setup.

**Comment by ayoayco** [comment]
@fazzaamiarso Very interested in this. Looks like it will save us a lot of manual work. 🙏

**Comment by fazzaamiarso** [comment]
@ayoayco do you want to try implement changeset manually before adding automation? So, we can get familiar with the commands beforehand.

Manual changeset workflow should be similar to our usual versioning and publishing workflow.

**Comment by ayoayco** [comment]
@fazzaamiarso Yup! Does this branch have working `changesets` cli?

**Comment by fazzaamiarso** [comment]
Yes, it's working. It also comes with Github action that automatically creates a versioning PR.

 I suggest to [read the docs](https://github.com/changesets/changesets/tree/main/docs). Here are some useful parts.
- [release beta, experimental, etc.](https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md)
- [cli option](https://github.com/changesets/changesets/blob/main/docs/command-line-options.md)
- [quickstart](https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md)
- [some faq](https://github.com/changesets/changesets/blob/main/docs/common-questions.md)

**Comment by ayoayco** [comment]
@fazzaamiarso Played around with changesets. Can you resolve conflicts so we can merge this? I want to test further the GH Actions. :)

**Review by ayoayco — CHANGES_REQUESTED** [review]
This looks great to merge now, I think you just need to update the package lock ;)

**Review by ayoayco — DISMISSED** [review]
Ah no worries, it was easy. I updated the package lock.

**Comment by ayoayco** [comment]
We're now getting a weird CI error regarding `turbo` not being found for this branch. Found a discussion and their resolution was this could be a caching issue, but our current CI does not have any caches https://github.com/vercel/turbo/issues/824

**Comment by fazzaamiarso** [comment]
Hey @ayoayco Sorry I've been very busy this time around, will get back at you this week.

**Comment by ayoayco** [comment]
Hey, no worries! Could you pick it up when you have the time? @fazzaamiarso

**Comment by ayoayco** [comment]
Updating turbo in our main branch fixed this. :) Just get the latest main branch and this should be fine.

**Comment by fazzaamiarso** [comment]
@ayoayco I'm checking it now

**Comment by ayoayco** [comment]
@fazzaamiarso 👍 - I tried some changes but really couldn't make the CI error go away. Was wondering if it's just cached, but after deleting our GH Action caches still there 🤔

**Comment by fazzaamiarso** [comment]
@ayoayco I moved the PR to #261. It seems the package-lock conflict is the problem. I fresh installed changeset from the recent main branch and it worked.

**Comment by ayoayco** [comment]
Closing this one then

**Pull request closed without merging**
