### PR TITLE
refactor(docs): implement new Style to define layouts

### PR DESCRIPTION
**Pull request by sacarvy**
## refactor(docs): Experimented with a new Style to define layouts.

Description of changes: 
- Added Base Layout
  - No HTML
  - SEO Handling
  - No JavaScript Check it out!
  - TypeScript
- Removed HeadCommon
- Removed HeadSEO

#### Sorry, Prettier config is different for me.

Tag a reviewer: @ayoayco  @jmakhack @AllanSiqueira

### CODE REVIEW

**Comment by sacarvy** [comment]
AstroReactivity, https://github.com/sacarvy/astro-reactive

**Comment by Preet-Sojitra** [comment]
@ayoayco It's high time that we add some configuration for prettier that will be same for all the contributors because I can see that because of prettier configuration so many lines of code have been changed

**Comment by ayoayco** [comment]
I agree regarding the prettier config @Preet-Sojitra. Thanks!

**Comment by ayoayco** [comment]
Thanks for this PR @sacarvy!

I just need some time to check this locally, because we recently moved the repository and now the automatic Netlify previews are not working 😅

**Comment by sacarvy** [comment]
Let me try to setup Prettier Config, along with `.editorconfig`

**Comment by sacarvy** [comment]
image

Does anyone, have built some design for docs, I might need some help here, functionality is almost ready and working
like highlighting, the active section.

Thanks

**Comment by sacarvy** [comment]
making it not exactly, like one at tailwindcss.com has but similar to that is possible, 
let me experiment with design.

**Comment by ayoayco** [comment]
> Does anyone, have built some design for docs

@sacarvy We don't have design for the docs site, but we are indeed open to a design overhaul. What we have now is just the default styling we got from astro-docs. Let me know if you need some input as well. If you want you can join our [discord](https://discord.gg/yKyzCjNK) -- we can have a channel ther for the docs site.

**Comment by ayoayco** [comment]
@sacarvy Can you resolve the merge conflicts so that Netlify preview will be triggered?

**Comment by sacarvy** [comment]
Yes, doing it

**Comment by sacarvy** [comment]
Still, in development. Don’t merge right now!

**Comment by ayoayco** [comment]
> Still, in development. Don’t merge right now!

@sacarvy okay! I think you can also mark as Draft for this.

**Comment by sacarvy** [comment]
checkout new design, of TabelOfContent

**Review by ayoayco — CHANGES_REQUESTED** [review]
Some requests:
1. fix the "undefined" text in the web title (see tab title pointed at by red arrow)
2. Let's keep the previews table of contents header, which was "ON THIS PAGE"
3. remove the background of table of contents header (encircled red)

Screenshot 2023-01-08 at 4 25 45 PM

**Comment by ayoayco** [comment]
Closing this for now as it will push a lot of changes we can't maintain moving forward.

**Pull request closed without merging**
